apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: api-app
    version: "blue"
  name: api-app-blue
spec:
  replicas: 2
  selector:
    matchLabels:
      app: api-app
      version: "blue"
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: api-app
        version: "blue"
    spec:
      containers:
      - image: us-central1-docker.pkg.dev/iit-cc/iit-cc/api-app:2.0.0
        name: api-app
        env:
            - name: DB_HOST
              valueFrom:
                secretKeyRef:
                  name: db-credentials
                  key: DB_HOST
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: db-credentials
                  key: DB_USER
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-credentials
                  key: DB_PASSWORD
            - name: DB_NAME
              valueFrom:
                configMapKeyRef:
                  name: db-config
                  key: DB_NAME
            - name: ENV
              valueFrom:
                configMapKeyRef:
                  name: db-config
                  key: ENV
        resources: {}
status: {}
---
apiVersion: "autoscaling/v2"
kind: "HorizontalPodAutoscaler"
metadata:
  name: "api-app-hpa-nfha"
  namespace: "default"
  labels:
    app: "node-app"
spec:
  scaleTargetRef:
    kind: "Deployment"
    name: "api-app-blue"
    apiVersion: "apps/v1"
  minReplicas: 1
  maxReplicas: 5
  metrics:
  - type: "Resource"
    resource:
      name: "cpu"
      target:
        type: "Utilization"
        averageUtilization: 80

