apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: api-app
    version: "green"
  name: api-app-green
spec:
  replicas: 2
  selector:
    matchLabels:
      app: api-app
      version: "green"
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: api-app
        version: "green"
    spec:
      containers:
      - image: us-central1-docker.pkg.dev/iit-cc/iit-cc/api-app:3.0.0
        name: api-app
        env:
            - name: DB_HOST
              valueFrom:
                secretKeyRef:
                  name: db-credentials
                  key: DB_HOST
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: db-credentials
                  key: DB_USER
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-credentials
                  key: DB_PASSWORD
            - name: DB_NAME
              valueFrom:
                configMapKeyRef:
                  name: db-config
                  key: DB_NAME
            - name: ENV
              valueFrom:
                configMapKeyRef:
                  name: db-config
                  key: ENV
        resources: {}
status: {}
