apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: api-app-green
  name: api-app-green
spec:
  replicas: 2
  selector:
    matchLabels:
      app: api-app-green
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: api-app-green
        color: green  # Added new label color: green
    spec:
      containers:
      - image: us-central1-docker.pkg.dev/iit-cc/iit-cc/api-app:2.0.0
        name: api-app
        env:
          - name: DB_HOST
            valueFrom:
              secretKeyRef:
                name: db-credentials
                key: DB_HOST
          - name: DB_USER
            valueFrom:
              secretKeyRef:
                name: db-credentials
                key: DB_USER
          - name: DB_PASSWORD
            valueFrom:
              secretKeyRef:
                name: db-credentials
                key: DB_PASSWORD
          - name: DB_NAME
            valueFrom:
              configMapKeyRef:
                name: db-config
                key: DB_NAME
          - name: ENV
            valueFrom:
              configMapKeyRef:
                name: db-config
                key: ENV
        resources: {}
status: {}

---

apiVersion: "autoscaling/v2"
kind: "HorizontalPodAutoscaler"
metadata:
  name: "api-app-hpa-nfha-green"
  namespace: "default"
  labels:
    app: "api-app"
spec:
  scaleTargetRef:
    kind: "Deployment"
    name: "api-app-green"  # Updated name to api-app-green
    apiVersion: "apps/v1"
  minReplicas: 1
  maxReplicas: 5
  metrics:
  - type: "Resource"
    resource:
      name: "cpu"
      target:
        type: "Utilization"
        averageUtilization: 80

---

apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: api-app-green
  name: api-app-service-green
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: api-app-green
  type: NodePort
status:
  loadBalancer: {}
