
name: Blue - Green Deployment

on:
  workflow_dispatch:
    inputs:
      color:
        description: 'Deployment type blue/green'
        default: 'green'
        required: false
        type: choice
        options:
          - blue
          - green
      tag:
        description: 'Deploy Version'
        default: '1.0.0'
        required: true
        type: string

env:
  IMAGE: api-app
  GKE_CLUSTER: prod-cluster-iit    
  GKE_ZONE: us-central1
  CONTAINER: api-app
  REPO: us-central1-docker.pkg.dev/iit-cc/iit-cc 

jobs:
  deploy-to-production:
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'

    steps:

      - name: Check out code
        uses: actions/checkout@v4.1.1
        
      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2.0.0
        with:
          credentials_json: '${{ secrets.GOOGLE_CREDENTIALS }}'
      
      - name: Set up GKE credentials
        uses: google-github-actions/get-gke-credentials@v1
        with:
          cluster_name: ${{ env.GKE_CLUSTER }}
          location: ${{ env.GKE_ZONE }}

      # Deploy the Docker image to the GKE cluster
      - name: Deploy Blue/Green to Kubernetes
        run: |
          # Determine which color to deploy based on input color
          if [ "${{ github.event.inputs.color }}" == blue ]; then
            kubectl apply -f deployments/api-version-blue.yaml
            # Enforce Application version
            kubectl set image deployment/api-app-blue $CONTAINER=$REPO/api-app:'${{ inputs.tag }}'
            kubectl rollout status deployment/api-app-blue
          elif [ "${{ github.event.inputs.color }}" == green ]; then
            kubectl apply -f deployments/api-version-green.yaml
            # Enforce Application version
            kubectl set image deployment/api-app-green $CONTAINER=$REPO/api-app:'${{ inputs.tag }}'
            kubectl rollout status deployment/api-app-green
          else
            echo "Invalid color provided. Please provide 'blue' or 'green'."
            exit 1
          fi

      - name: Update Service for Traffic Switching
        if: success()
        run: |
          if [ "${{ github.event.inputs.color }}" == blue ]; then
            kubectl apply -f deployments/svc-blue.yaml
          else
            kubectl apply -f deployments/svc-green.yaml
          fi

          
    
